apiVersion: apps/v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-db
  name: mysql-db
spec:
  tags:
  - annotations: {}
    from:
      kind: DockerImage
      name: mysql
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
